### YamlMime:ManagedReference
items:
- uid: Terminal.Gui.ConfigurationManager.ConfigLocations
  commentId: T:Terminal.Gui.ConfigurationManager.ConfigLocations
  id: ConfigurationManager.ConfigLocations
  parent: Terminal.Gui
  children:
  - Terminal.Gui.ConfigurationManager.ConfigLocations.All
  - Terminal.Gui.ConfigurationManager.ConfigLocations.DefaultOnly
  - Terminal.Gui.ConfigurationManager.ConfigLocations.None
  langs:
  - csharp
  - vb
  name: ConfigurationManager.ConfigLocations
  nameWithType: ConfigurationManager.ConfigLocations
  fullName: Terminal.Gui.ConfigurationManager.ConfigLocations
  type: Enum
  source:
    remote:
      path: Terminal.Gui/Configuration/ConfigurationManager.cs
      branch: v2_develop
      repo: tig:tig/Terminal.Gui.git
    id: ConfigLocations
    path: ../Terminal.Gui/Configuration/ConfigurationManager.cs
    startLine: 365
  assemblies:
  - Terminal.Gui
  namespace: Terminal.Gui
  summary: >-
    Describes the location of the configuration files. The constants can be

    combined (bitwise) to specify multiple locations.
  example: []
  syntax:
    content: >-
      [Flags]

      public enum ConfigurationManager.ConfigLocations
    content.vb: >-
      <Flags>

      Public Enum ConfigurationManager.ConfigLocations
  attributes:
  - type: System.FlagsAttribute
    ctor: System.FlagsAttribute.#ctor
    arguments: []
- uid: Terminal.Gui.ConfigurationManager.ConfigLocations.None
  commentId: F:Terminal.Gui.ConfigurationManager.ConfigLocations.None
  id: None
  parent: Terminal.Gui.ConfigurationManager.ConfigLocations
  langs:
  - csharp
  - vb
  name: None
  nameWithType: ConfigurationManager.ConfigLocations.None
  fullName: Terminal.Gui.ConfigurationManager.ConfigLocations.None
  type: Field
  source:
    remote:
      path: Terminal.Gui/Configuration/ConfigurationManager.cs
      branch: v2_develop
      repo: tig:tig/Terminal.Gui.git
    id: None
    path: ../Terminal.Gui/Configuration/ConfigurationManager.cs
    startLine: 374
  assemblies:
  - Terminal.Gui
  namespace: Terminal.Gui
  summary: No configuration will be loaded.
  remarks: >-
    Used for development and testing only. For Terminal,Gui to function properly, at least

    <xref href="Terminal.Gui.ConfigurationManager.ConfigLocations.DefaultOnly" data-throw-if-not-resolved="false"></xref> should be set.
  example: []
  syntax:
    content: None = 0
    return:
      type: Terminal.Gui.ConfigurationManager.ConfigLocations
- uid: Terminal.Gui.ConfigurationManager.ConfigLocations.DefaultOnly
  commentId: F:Terminal.Gui.ConfigurationManager.ConfigLocations.DefaultOnly
  id: DefaultOnly
  parent: Terminal.Gui.ConfigurationManager.ConfigLocations
  langs:
  - csharp
  - vb
  name: DefaultOnly
  nameWithType: ConfigurationManager.ConfigLocations.DefaultOnly
  fullName: Terminal.Gui.ConfigurationManager.ConfigLocations.DefaultOnly
  type: Field
  source:
    remote:
      path: Terminal.Gui/Configuration/ConfigurationManager.cs
      branch: v2_develop
      repo: tig:tig/Terminal.Gui.git
    id: DefaultOnly
    path: ../Terminal.Gui/Configuration/ConfigurationManager.cs
    startLine: 379
  assemblies:
  - Terminal.Gui
  namespace: Terminal.Gui
  summary: Global configuration in <code>Terminal.Gui.dll</code>'s resources (<code>Terminal.Gui.Resources.config.json</code>) -- Lowest Precidence.
  example: []
  syntax:
    content: DefaultOnly = 1
    return:
      type: Terminal.Gui.ConfigurationManager.ConfigLocations
- uid: Terminal.Gui.ConfigurationManager.ConfigLocations.All
  commentId: F:Terminal.Gui.ConfigurationManager.ConfigLocations.All
  id: All
  parent: Terminal.Gui.ConfigurationManager.ConfigLocations
  langs:
  - csharp
  - vb
  name: All
  nameWithType: ConfigurationManager.ConfigLocations.All
  fullName: Terminal.Gui.ConfigurationManager.ConfigLocations.All
  type: Field
  source:
    remote:
      path: Terminal.Gui/Configuration/ConfigurationManager.cs
      branch: v2_develop
      repo: tig:tig/Terminal.Gui.git
    id: All
    path: ../Terminal.Gui/Configuration/ConfigurationManager.cs
    startLine: 384
  assemblies:
  - Terminal.Gui
  namespace: Terminal.Gui
  summary: This constant is a combination of all locations
  example: []
  syntax:
    content: All = -1
    return:
      type: Terminal.Gui.ConfigurationManager.ConfigLocations
references:
- uid: Terminal.Gui
  commentId: N:Terminal.Gui
  href: Terminal.html
  name: Terminal.Gui
  nameWithType: Terminal.Gui
  fullName: Terminal.Gui
  spec.csharp:
  - uid: Terminal
    name: Terminal
    href: Terminal.html
  - name: .
  - uid: Terminal.Gui
    name: Gui
    href: Terminal.Gui.html
  spec.vb:
  - uid: Terminal
    name: Terminal
    href: Terminal.html
  - name: .
  - uid: Terminal.Gui
    name: Gui
    href: Terminal.Gui.html
- uid: Terminal.Gui.ConfigurationManager.ConfigLocations.DefaultOnly
  commentId: F:Terminal.Gui.ConfigurationManager.ConfigLocations.DefaultOnly
  href: Terminal.Gui.ConfigurationManager.ConfigLocations.html#Terminal.Gui.ConfigurationManager.ConfigLocations.DefaultOnly
  name: DefaultOnly
  nameWithType: ConfigurationManager.ConfigLocations.DefaultOnly
  fullName: Terminal.Gui.ConfigurationManager.ConfigLocations.DefaultOnly
- uid: Terminal.Gui.ConfigurationManager.ConfigLocations
  commentId: T:Terminal.Gui.ConfigurationManager.ConfigLocations
  parent: Terminal.Gui
  href: Terminal.Gui.ConfigurationManager.html
  name: ConfigurationManager.ConfigLocations
  nameWithType: ConfigurationManager.ConfigLocations
  fullName: Terminal.Gui.ConfigurationManager.ConfigLocations
  spec.csharp:
  - uid: Terminal.Gui.ConfigurationManager
    name: ConfigurationManager
    href: Terminal.Gui.ConfigurationManager.html
  - name: .
  - uid: Terminal.Gui.ConfigurationManager.ConfigLocations
    name: ConfigLocations
    href: Terminal.Gui.ConfigurationManager.ConfigLocations.html
  spec.vb:
  - uid: Terminal.Gui.ConfigurationManager
    name: ConfigurationManager
    href: Terminal.Gui.ConfigurationManager.html
  - name: .
  - uid: Terminal.Gui.ConfigurationManager.ConfigLocations
    name: ConfigLocations
    href: Terminal.Gui.ConfigurationManager.ConfigLocations.html
shouldSkipMarkup: true
