name: Build and publish API docs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # ...
    - name: Use docfx to build API Docs
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docfx/docfx.json

    # # Publish generated site using GitHub Pages
    # - uses: maxheld83/ghpages@master
    #   name: Publish API Documentation on GitHub Pages
    #   env:
    #     BUILD_DIR: docs # docfx's default output directory is _site
    #     GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages